id: I97911AB8
ocr_import_info:
  timestamp: '2023-08-16T06:25:56.816186+00:00'
  batch_id: batch-79f1
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-16 06:40:01.858057+00:00
last_modified: 2023-08-16 06:40:01.858066+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM956
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM956
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་རྩ་བ་ཤེས་རབ་ཀྱི་ངག་དོན་བཤད་པ་རིན་པོ་ཆེའི་ཕྲེང་བ་སོགས།
  languages:
  - bo
  author: འཇམ་དབྱངས་བཞད་པ ༠༡་ངག་དབང་བརྩོན་འགྲུས།
statistics:
  ocr_word_mean_confidence_index: 0.9507261921228325
  ocr_word_median_confidence_index: 0.99510438
bases:
  I1NLM956_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM956_001
      total_pages: 168
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM956_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.99510438
      ocr_word_mean_confidence_index: 0.9507261921228325
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
